version: "3.9"

services:
  postgres_db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  web:
    build:
      context: .
    container_name: web
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  react_app:
    build:
      context: ./path/to/react/app
    container_name: react_app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
